//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17626
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power8.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This localization is done by Power8 Team.
        /// </summary>
        internal static string CR_AbLocalization {
            get {
                return ResourceManager.GetString("CR_AbLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version:.
        /// </summary>
        internal static string CR_AbVersion {
            get {
                return ResourceManager.GetString("CR_AbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open All Users Folder.
        /// </summary>
        internal static string CR_AppOpenCommonFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenCommonFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Location.
        /// </summary>
        internal static string CR_AppOpenContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string CR_AppOpenFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Target Location.
        /// </summary>
        internal static string CR_AppOpenTargetContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenTargetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run.
        /// </summary>
        internal static string CR_AppRun {
            get {
                return ResourceManager.GetString("CR_AppRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run as Administrator.
        /// </summary>
        internal static string CR_AppRunAs {
            get {
                return ResourceManager.GetString("CR_AppRunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string CR_AppShowProperties {
            get {
                return ResourceManager.GetString("CR_AppShowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target Properties.
        /// </summary>
        internal static string CR_AppShowTargetProperties {
            get {
                return ResourceManager.GetString("CR_AppShowTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hibernate.
        /// </summary>
        internal static string CR_ButtonHibernate {
            get {
                return ResourceManager.GetString("CR_ButtonHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock PC.
        /// </summary>
        internal static string CR_ButtonLock {
            get {
                return ResourceManager.GetString("CR_ButtonLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log Off.
        /// </summary>
        internal static string CR_ButtonLogOff {
            get {
                return ResourceManager.GetString("CR_ButtonLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        internal static string CR_ButtonRestart {
            get {
                return ResourceManager.GetString("CR_ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Run....
        /// </summary>
        internal static string CR_ButtonRun {
            get {
                return ResourceManager.GetString("CR_ButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Screensaver.
        /// </summary>
        internal static string CR_ButtonScreensave {
            get {
                return ResourceManager.GetString("CR_ButtonScreensave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown.
        /// </summary>
        internal static string CR_ButtonShutdown {
            get {
                return ResourceManager.GetString("CR_ButtonShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sleep.
        /// </summary>
        internal static string CR_ButtonSleep {
            get {
                return ResourceManager.GetString("CR_ButtonSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power8 - Start Menu replacer for Windows XP, Se7en and 8.
        /// </summary>
        internal static string CR_ButtonStack {
            get {
                return ResourceManager.GetString("CR_ButtonStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string CR_CLCleanerBtn {
            get {
                return ResourceManager.GetString("CR_CLCleanerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computers list.
        /// </summary>
        internal static string CR_CLWindow {
            get {
                return ResourceManager.GetString("CR_CLWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Item(s).
        /// </summary>
        internal static string CR_GroupItemsText {
            get {
                return ResourceManager.GetString("CR_GroupItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string CR_MWAbout {
            get {
                return ResourceManager.GetString("CR_MWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Start.
        /// </summary>
        internal static string CR_MWAutoStart {
            get {
                return ResourceManager.GetString("CR_MWAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block Metro features.
        /// </summary>
        internal static string CR_MWBlockMetro {
            get {
                return ResourceManager.GetString("CR_MWBlockMetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for Updates.
        /// </summary>
        internal static string CR_MWCheckForUpdates {
            get {
                return ResourceManager.GetString("CR_MWCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string CR_MWExit {
            get {
                return ResourceManager.GetString("CR_MWExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search....
        /// </summary>
        internal static string CR_SearchBox {
            get {
                return ResourceManager.GetString("CR_SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Searching....
        /// </summary>
        internal static string CR_SearchMarker {
            get {
                return ResourceManager.GetString("CR_SearchMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download 7z.
        /// </summary>
        internal static string CR_UNdown7z {
            get {
                return ResourceManager.GetString("CR_UNdown7z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download MSI and update now!.
        /// </summary>
        internal static string CR_UNDownAndUp {
            get {
                return ResourceManager.GetString("CR_UNDownAndUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download MSI.
        /// </summary>
        internal static string CR_UNdownMsi {
            get {
                return ResourceManager.GetString("CR_UNdownMsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open project web site.
        /// </summary>
        internal static string CR_UNGoWeb {
            get {
                return ResourceManager.GetString("CR_UNGoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t tell me again about this update.
        /// </summary>
        internal static string CR_UNIgnore {
            get {
                return ResourceManager.GetString("CR_UNIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version:.
        /// </summary>
        internal static string CR_UNNewVersion {
            get {
                return ResourceManager.GetString("CR_UNNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remind me next time.
        /// </summary>
        internal static string CR_UNNextTime {
            get {
                return ResourceManager.GetString("CR_UNNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other options:.
        /// </summary>
        internal static string CR_UNOther {
            get {
                return ResourceManager.GetString("CR_UNOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An update is available to Power8!.
        /// </summary>
        internal static string CR_UNUpdateAvailableLong {
            get {
                return ResourceManager.GetString("CR_UNUpdateAvailableLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update notification.
        /// </summary>
        internal static string CR_UNwnd {
            get {
                return ResourceManager.GetString("CR_UNwnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your version:.
        /// </summary>
        internal static string CR_UNYourVersion {
            get {
                return ResourceManager.GetString("CR_UNYourVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to check for updates.
        ///.
        /// </summary>
        internal static string Err_CantCheckUpdates {
            get {
                return ResourceManager.GetString("Err_CantCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get tooltip for object.
        /// </summary>
        internal static string Err_CantGetTooltip {
            get {
                return ResourceManager.GetString("Err_CantGetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to instanciate class {0}
        ///{1}.
        /// </summary>
        internal static string Err_CantInstanciateClassFormatString {
            get {
                return ResourceManager.GetString("Err_CantInstanciateClassFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading was cancelled..
        /// </summary>
        internal static string Err_DownloadCancelled {
            get {
                return ResourceManager.GetString("Err_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found for .
        /// </summary>
        internal static string Err_GotNoFile {
            get {
                return ResourceManager.GetString("Err_GotNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory not found for .
        /// </summary>
        internal static string Err_GotNoFolder {
            get {
                return ResourceManager.GetString("Err_GotNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data element available.
        /// </summary>
        internal static string Err_NoPiExtracted {
            get {
                return ResourceManager.GetString("Err_NoPiExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error {0} caused while trying to show object Properties
        ///{1}.
        /// </summary>
        internal static string Err_ShellExecExErrorFormatString {
            get {
                return ResourceManager.GetString("Err_ShellExecExErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to start specified object as Administrator. Process launched with regular user rights.
        ///.
        /// </summary>
        internal static string Err_StartAsAdminFailed {
            get {
                return ResourceManager.GetString("Err_StartAsAdminFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows (R) Vista (R) is not intended to be used with Power8. Please use normal operating system..
        /// </summary>
        internal static string Err_VistaDetected {
            get {
                return ResourceManager.GetString("Err_VistaDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Programs.
        /// </summary>
        internal static string Str_AllPrograms {
            get {
                return ResourceManager.GetString("Str_AllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control panel element.
        /// </summary>
        internal static string Str_CplElement {
            get {
                return ResourceManager.GetString("Str_CplElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  (library).
        /// </summary>
        internal static string Str_Library {
            get {
                return ResourceManager.GetString("Str_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Str_LocalizerUri {
            get {
                return ResourceManager.GetString("Str_LocalizerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin item.
        /// </summary>
        internal static string Str_Pin {
            get {
                return ResourceManager.GetString("Str_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recently started.
        /// </summary>
        internal static string Str_Recent {
            get {
                return ResourceManager.GetString("Str_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на : choose where to download the file.
        /// </summary>
        internal static string Str_SaveDialogDescription {
            get {
                return ResourceManager.GetString("Str_SaveDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  update|*.
        /// </summary>
        internal static string Str_SaveDialogFilter {
            get {
                return ResourceManager.GetString("Str_SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show more....
        /// </summary>
        internal static string Str_ShowMore {
            get {
                return ResourceManager.GetString("Str_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unpin item.
        /// </summary>
        internal static string Str_Unpin {
            get {
                return ResourceManager.GetString("Str_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на : update available!.
        /// </summary>
        internal static string Str_UpdateAvailable {
            get {
                return ResourceManager.GetString("Str_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///Your version: {0}
        ///New version: {1}
        ///
        ///Do you want to go to the website and update?
        ///
        ///Yes: go to web site and update now!
        ///No: remind me later, please.
        ///Cancel: I skip this update, never notify me about this version..
        /// </summary>
        internal static string Str_UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("Str_UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Search Results.
        /// </summary>
        internal static string Str_WindowsSearchResults {
            get {
                return ResourceManager.GetString("Str_WindowsSearchResults", resourceCulture);
            }
        }
    }
}
