//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit WebMoney site to donate Power8 team.
        /// </summary>
        internal static string CR_AbDonate {
            get {
                return ResourceManager.GetString("CR_AbDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This localization is done by Power8 Team.
        /// </summary>
        internal static string CR_AbLocalization {
            get {
                return ResourceManager.GetString("CR_AbLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string CR_AbVersion {
            get {
                return ResourceManager.GetString("CR_AbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from custom launch list.
        /// </summary>
        internal static string CR_AppExcludeFromCustom {
            get {
                return ResourceManager.GetString("CR_AppExcludeFromCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this item.
        /// </summary>
        internal static string CR_AppExcludeFromMfu {
            get {
                return ResourceManager.GetString("CR_AppExcludeFromMfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to custom launch list.
        /// </summary>
        internal static string CR_AppIncludeToCustom {
            get {
                return ResourceManager.GetString("CR_AppIncludeToCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All Users Folder.
        /// </summary>
        internal static string CR_AppOpenCommonFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenCommonFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location.
        /// </summary>
        internal static string CR_AppOpenContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CR_AppOpenFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Target Location.
        /// </summary>
        internal static string CR_AppOpenTargetContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenTargetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string CR_AppRun {
            get {
                return ResourceManager.GetString("CR_AppRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string CR_AppRunAs {
            get {
                return ResourceManager.GetString("CR_AppRunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string CR_AppShowProperties {
            get {
                return ResourceManager.GetString("CR_AppShowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Properties.
        /// </summary>
        internal static string CR_AppShowTargetProperties {
            get {
                return ResourceManager.GetString("CR_AppShowTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string CR_ButtonHibernate {
            get {
                return ResourceManager.GetString("CR_ButtonHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock PC.
        /// </summary>
        internal static string CR_ButtonLock {
            get {
                return ResourceManager.GetString("CR_ButtonLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string CR_ButtonLogOff {
            get {
                return ResourceManager.GetString("CR_ButtonLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string CR_ButtonRestart {
            get {
                return ResourceManager.GetString("CR_ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run....
        /// </summary>
        internal static string CR_ButtonRun {
            get {
                return ResourceManager.GetString("CR_ButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Screensaver.
        /// </summary>
        internal static string CR_ButtonScreensave {
            get {
                return ResourceManager.GetString("CR_ButtonScreensave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string CR_ButtonShutdown {
            get {
                return ResourceManager.GetString("CR_ButtonShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string CR_ButtonSleep {
            get {
                return ResourceManager.GetString("CR_ButtonSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power8 - Start Menu replacer for Windows XP, Se7en and 8.
        /// </summary>
        internal static string CR_ButtonStack {
            get {
                return ResourceManager.GetString("CR_ButtonStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch User.
        /// </summary>
        internal static string CR_ButtonSwitchUser {
            get {
                return ResourceManager.GetString("CR_ButtonSwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CR_CLCleanerBtn {
            get {
                return ResourceManager.GetString("CR_CLCleanerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computers list.
        /// </summary>
        internal static string CR_CLWindow {
            get {
                return ResourceManager.GetString("CR_CLWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Item(s).
        /// </summary>
        internal static string CR_GroupItemsText {
            get {
                return ResourceManager.GetString("CR_GroupItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        internal static string CR_MWAbout {
            get {
                return ResourceManager.GetString("CR_MWAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        internal static string CR_MWAutoStart {
            get {
                return ResourceManager.GetString("CR_MWAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Metro features.
        /// </summary>
        internal static string CR_MWBlockMetro {
            get {
                return ResourceManager.GetString("CR_MWBlockMetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CR_MWCheckForUpdates {
            get {
                return ResourceManager.GetString("CR_MWCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate Power8 Team....
        /// </summary>
        internal static string CR_MWDonate {
            get {
                return ResourceManager.GetString("CR_MWDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CR_MWExit {
            get {
                return ResourceManager.GetString("CR_MWExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string CR_MWSettings {
            get {
                return ResourceManager.GetString("CR_MWSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        ///I know what&apos;s happening and will handle the problem myself..
        /// </summary>
        internal static string CR_RE_NoButton {
            get {
                return ResourceManager.GetString("CR_RE_NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power8 — Windows Explorer is dead.
        /// </summary>
        internal static string CR_RE_Title {
            get {
                return ResourceManager.GetString("CR_RE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that Windows Explorer process is unavailable.
        ///Power8 can help you handling this.
        /// 
        ///Do you want to restore Windows Explorer and restart Power8?.
        /// </summary>
        internal static string CR_RE_TopLabel {
            get {
                return ResourceManager.GetString("CR_RE_TopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes!
        ///Please launch Explorer for me and restart Power8 process..
        /// </summary>
        internal static string CR_RE_YesButton {
            get {
                return ResourceManager.GetString("CR_RE_YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string CR_SearchBox {
            get {
                return ResourceManager.GetString("CR_SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string CR_SearchMarker {
            get {
                return ResourceManager.GetString("CR_SearchMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (by Desktop).
        /// </summary>
        internal static string CR_StgArByDesktop {
            get {
                return ResourceManager.GetString("CR_StgArByDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Main window close to mouse after Alt+Z.
        /// </summary>
        internal static string CR_StgAutoCorner {
            get {
                return ResourceManager.GetString("CR_StgAutoCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application when fatal error occurs.
        /// </summary>
        internal static string CR_StgAutoRestart {
            get {
                return ResourceManager.GetString("CR_StgAutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-sort menus and lists when file or folder is added or renamed.
        /// </summary>
        internal static string CR_StgAutoSort {
            get {
                return ResourceManager.GetString("CR_StgAutoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string CR_StgBrowseBtn {
            get {
                return ResourceManager.GetString("CR_StgBrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Control Panel with items sorted by category.
        /// </summary>
        internal static string CR_StgCbCtrl {
            get {
                return ResourceManager.GetString("CR_StgCbCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange All programs menu and Search bar for better usability.
        /// </summary>
        internal static string CR_StgDynamicLayout {
            get {
                return ResourceManager.GetString("CR_StgDynamicLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows taskbar orientation.
        /// </summary>
        internal static string CR_StgInvertAr {
            get {
                return ResourceManager.GetString("CR_StgInvertAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio:.
        /// </summary>
        internal static string CR_StgLblAr {
            get {
                return ResourceManager.GetString("CR_StgLblAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image (doubleclick path to clear):.
        /// </summary>
        internal static string CR_StgLblChooseImage {
            get {
                return ResourceManager.GetString("CR_StgLblChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;All programs&quot; text (clear to use system defaults):.
        /// </summary>
        internal static string CR_StgLblSetStartText {
            get {
                return ResourceManager.GetString("CR_StgLblSetStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu-buttons:.
        /// </summary>
        internal static string CR_StgLblShowMenuButtons {
            get {
                return ResourceManager.GetString("CR_StgLblShowMenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch image:.
        /// </summary>
        internal static string CR_StgLblStretch {
            get {
                return ResourceManager.GetString("CR_StgLblStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide items containing strings:.
        /// </summary>
        internal static string CR_StgMfuColExcl {
            get {
                return ResourceManager.GetString("CR_StgMfuColExcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom list (user-configurable).
        /// </summary>
        internal static string CR_StgMfuUseCustom {
            get {
                return ResourceManager.GetString("CR_StgMfuUseCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Power8 internal data.
        /// </summary>
        internal static string CR_StgMfuUseP8JL {
            get {
                return ResourceManager.GetString("CR_StgMfuUseP8JL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system data (UserAssist) to build list.
        /// </summary>
        internal static string CR_StgMfuUseSystem {
            get {
                return ResourceManager.GetString("CR_StgMfuUseSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Donate menu item.
        /// </summary>
        internal static string CR_StgShowDonateMenuItem {
            get {
                return ResourceManager.GetString("CR_StgShowDonateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Start button.
        /// </summary>
        internal static string CR_StgSquareStart {
            get {
                return ResourceManager.GetString("CR_StgSquareStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill whole button.
        /// </summary>
        internal static string CR_StgStrFill {
            get {
                return ResourceManager.GetString("CR_StgStrFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not stretch.
        /// </summary>
        internal static string CR_StgStrNone {
            get {
                return ResourceManager.GetString("CR_StgStrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform scaling.
        /// </summary>
        internal static string CR_StgStrUniform {
            get {
                return ResourceManager.GetString("CR_StgStrUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform-to-fill scaling.
        /// </summary>
        internal static string CR_StgStrUniform2Fill {
            get {
                return ResourceManager.GetString("CR_StgStrUniform2Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform me about configuration issues.
        /// </summary>
        internal static string CR_StgSuggestProblems {
            get {
                return ResourceManager.GetString("CR_StgSuggestProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CR_StgTabGeneral {
            get {
                return ResourceManager.GetString("CR_StgTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu-buttons.
        /// </summary>
        internal static string CR_StgTabMenuBtns {
            get {
                return ResourceManager.GetString("CR_StgTabMenuBtns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most frequently used.
        /// </summary>
        internal static string CR_StgTabMfu {
            get {
                return ResourceManager.GetString("CR_StgTabMfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web search engines.
        /// </summary>
        internal static string CR_StgTabWSE {
            get {
                return ResourceManager.GetString("CR_StgTabWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch removable drives.
        /// </summary>
        internal static string CR_StgWatchRemovables {
            get {
                return ResourceManager.GetString("CR_StgWatchRemovables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power8 settings.
        /// </summary>
        internal static string CR_StgWnd {
            get {
                return ResourceManager.GetString("CR_StgWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string CR_StgWseColKey {
            get {
                return ResourceManager.GetString("CR_StgWseColKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string.
        /// </summary>
        internal static string CR_StgWseColVal {
            get {
                return ResourceManager.GetString("CR_StgWseColVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download 7z.
        /// </summary>
        internal static string CR_UNdown7z {
            get {
                return ResourceManager.GetString("CR_UNdown7z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download MSI and update now!.
        /// </summary>
        internal static string CR_UNDownAndUp {
            get {
                return ResourceManager.GetString("CR_UNDownAndUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download MSI.
        /// </summary>
        internal static string CR_UNdownMsi {
            get {
                return ResourceManager.GetString("CR_UNdownMsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project web site.
        /// </summary>
        internal static string CR_UNGoWeb {
            get {
                return ResourceManager.GetString("CR_UNGoWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t tell me again about this update.
        /// </summary>
        internal static string CR_UNIgnore {
            get {
                return ResourceManager.GetString("CR_UNIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        internal static string CR_UNNewVersion {
            get {
                return ResourceManager.GetString("CR_UNNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me next time.
        /// </summary>
        internal static string CR_UNNextTime {
            get {
                return ResourceManager.GetString("CR_UNNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other options:.
        /// </summary>
        internal static string CR_UNOther {
            get {
                return ResourceManager.GetString("CR_UNOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available to Power8!.
        /// </summary>
        internal static string CR_UNUpdateAvailableLong {
            get {
                return ResourceManager.GetString("CR_UNUpdateAvailableLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update notification.
        /// </summary>
        internal static string CR_UNwnd {
            get {
                return ResourceManager.GetString("CR_UNwnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version:.
        /// </summary>
        internal static string CR_UNYourVersion {
            get {
                return ResourceManager.GetString("CR_UNYourVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates..
        /// </summary>
        internal static string Err_CantCheckUpdates {
            get {
                return ResourceManager.GetString("Err_CantCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get tooltip for object.
        /// </summary>
        internal static string Err_CantGetTooltip {
            get {
                return ResourceManager.GetString("Err_CantGetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instanciate class {0}
        ///{1}.
        /// </summary>
        internal static string Err_CantInstanciateClassFormatString {
            get {
                return ResourceManager.GetString("Err_CantInstanciateClassFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading was cancelled..
        /// </summary>
        internal static string Err_DownloadCancelled {
            get {
                return ResourceManager.GetString("Err_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found for .
        /// </summary>
        internal static string Err_GotNoFile {
            get {
                return ResourceManager.GetString("Err_GotNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found for .
        /// </summary>
        internal static string Err_GotNoFolder {
            get {
                return ResourceManager.GetString("Err_GotNoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data element available.
        /// </summary>
        internal static string Err_NoPiExtracted {
            get {
                return ResourceManager.GetString("Err_NoPiExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} caused while trying to show object Properties
        ///{1}.
        /// </summary>
        internal static string Err_ShellExecExErrorFormatString {
            get {
                return ResourceManager.GetString("Err_ShellExecExErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start specified object as Administrator. Process launched with regular user rights.
        ///.
        /// </summary>
        internal static string Err_StartAsAdminFailed {
            get {
                return ResourceManager.GetString("Err_StartAsAdminFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (R) Vista (R) is not intended to be used with Power8. Please use normal operating system..
        /// </summary>
        internal static string Err_VistaDetected {
            get {
                return ResourceManager.GetString("Err_VistaDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Programs.
        /// </summary>
        internal static string Str_AllPrograms {
            get {
                return ResourceManager.GetString("Str_AllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel element.
        /// </summary>
        internal static string Str_CplElement {
            get {
                return ResourceManager.GetString("Str_CplElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (library).
        /// </summary>
        internal static string Str_Library {
            get {
                return ResourceManager.GetString("Str_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Str_LocalizerUri {
            get {
                return ResourceManager.GetString("Str_LocalizerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : choose the Start Menu picture.
        /// </summary>
        internal static string Str_PicDialogDescription {
            get {
                return ResourceManager.GetString("Str_PicDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Str_PicDialogFilter {
            get {
                return ResourceManager.GetString("Str_PicDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin item.
        /// </summary>
        internal static string Str_Pin {
            get {
                return ResourceManager.GetString("Str_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently started.
        /// </summary>
        internal static string Str_Recent {
            get {
                return ResourceManager.GetString("Str_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : choose where to download the file.
        /// </summary>
        internal static string Str_SaveDialogDescription {
            get {
                return ResourceManager.GetString("Str_SaveDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  update|*.
        /// </summary>
        internal static string Str_SaveDialogFilter {
            get {
                return ResourceManager.GetString("Str_SaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more....
        /// </summary>
        internal static string Str_ShowMore {
            get {
                return ResourceManager.GetString("Str_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may wish to change some settings to enhance your Power8 experience.
        /// </summary>
        internal static string Str_TipWarn {
            get {
                return ResourceManager.GetString("Str_TipWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin item.
        /// </summary>
        internal static string Str_Unpin {
            get {
                return ResourceManager.GetString("Str_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : update available!.
        /// </summary>
        internal static string Str_UpdateAvailable {
            get {
                return ResourceManager.GetString("Str_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Your version: {0}
        ///New version: {1}
        ///
        ///Do you want to go to the website and update?
        ///
        ///Yes: go to web site and update now!
        ///No: remind me later, please.
        ///Cancel: I skip this update, never notify me about this version..
        /// </summary>
        internal static string Str_UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("Str_UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Search Results.
        /// </summary>
        internal static string Str_WindowsSearchResults {
            get {
                return ResourceManager.GetString("Str_WindowsSearchResults", resourceCulture);
            }
        }
    }
}
