//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power8.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Programs.
        /// </summary>
        internal static string AllPrograms {
            get {
                return ResourceManager.GetString("AllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power8.
        /// </summary>
        internal static string AppShortName {
            get {
                return ResourceManager.GetString("AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svn/trunk/Properties/AssemblyInfo.cs.
        /// </summary>
        internal static string AssemblyInfoURI {
            get {
                return ResourceManager.GetString("AssemblyInfoURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to check for updates.
        ///.
        /// </summary>
        internal static string CantCheckUpdates {
            get {
                return ResourceManager.GetString("CantCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All Users Folder.
        /// </summary>
        internal static string CR_AppOpenCommonFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenCommonFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location.
        /// </summary>
        internal static string CR_AppOpenContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CR_AppOpenFolder {
            get {
                return ResourceManager.GetString("CR_AppOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Target Location.
        /// </summary>
        internal static string CR_AppOpenTargetContainer {
            get {
                return ResourceManager.GetString("CR_AppOpenTargetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string CR_AppRun {
            get {
                return ResourceManager.GetString("CR_AppRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As....
        /// </summary>
        internal static string CR_AppRunAs {
            get {
                return ResourceManager.GetString("CR_AppRunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string CR_AppShowProperties {
            get {
                return ResourceManager.GetString("CR_AppShowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Properties.
        /// </summary>
        internal static string CR_AppShowTargetProperties {
            get {
                return ResourceManager.GetString("CR_AppShowTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string CR_ButtonHibernate {
            get {
                return ResourceManager.GetString("CR_ButtonHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock PC.
        /// </summary>
        internal static string CR_ButtonLock {
            get {
                return ResourceManager.GetString("CR_ButtonLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string CR_ButtonLogOff {
            get {
                return ResourceManager.GetString("CR_ButtonLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string CR_ButtonRestart {
            get {
                return ResourceManager.GetString("CR_ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run....
        /// </summary>
        internal static string CR_ButtonRun {
            get {
                return ResourceManager.GetString("CR_ButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Screensaver.
        /// </summary>
        internal static string CR_ButtonScreensave {
            get {
                return ResourceManager.GetString("CR_ButtonScreensave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string CR_ButtonShutdown {
            get {
                return ResourceManager.GetString("CR_ButtonShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string CR_ButtonSleep {
            get {
                return ResourceManager.GetString("CR_ButtonSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        internal static string CR_MWAutoStart {
            get {
                return ResourceManager.GetString("CR_MWAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CR_MWCheckForUpdates {
            get {
                return ResourceManager.GetString("CR_MWCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CR_MWExit {
            get {
                return ResourceManager.GetString("CR_MWExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting because {0}.
        /// </summary>
        internal static string FailFastFormat {
            get {
                return ResourceManager.GetString("FailFastFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://power8.googlecode.com/.
        /// </summary>
        internal static string Power8URI {
            get {
                return ResourceManager.GetString("Power8URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        internal static string RegKeyRun {
            get {
                return ResourceManager.GetString("RegKeyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} caused while trying to call ShellExecuteEx()!.
        /// </summary>
        internal static string ShellExecExErrorFormatString {
            get {
                return ResourceManager.GetString("ShellExecExErrorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start specified object as Administrator. Process launched with regular user rights..
        /// </summary>
        internal static string StartAsAdminFailed {
            get {
                return ResourceManager.GetString("StartAsAdminFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : update available!.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update available to Power8!
        ///
        ///Your version: {0}
        ///New version: {1}
        ///
        ///Do you want to go to the website and update? 
        ///
        ///Yes: go to web site and update now!
        ///No: remind me later, please.
        ///Cancel: I skip this update, never notify me about this version..
        /// </summary>
        internal static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
    }
}
