//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power8.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreVer {
            get {
                return ((string)(this["IgnoreVer"]));
            }
            set {
                this["IgnoreVer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRunDone {
            get {
                return ((bool)(this["FirstRunDone"]));
            }
            set {
                this["FirstRunDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-8""?>
<P8SearchProviders>
  <Provider key=""b"">http://www.bing.com/search?q={0}</Provider>
  <Provider key=""d"">http://www.baidu.com/s?wd={0}</Provider>
  <Provider key=""g"">https://google.com/search?q={0}</Provider>
  <Provider key=""w"">http://en.wikipedia.org/w/index.php?search={0}</Provider>
  <Provider key=""y"">http://yandex.com/yandsearch?text={0}</Provider>
  <Provider key=""в"">http://ru.wikipedia.org/w/index.php?search={0}</Provider>
  <Provider key=""г"">https://google.ru/search?q={0}</Provider>
  <Provider key=""я"">http://yandex.ru/yandsearch?text={0}</Provider>
</P8SearchProviders>")]
        public string SearchProviders {
            get {
                return ((string)(this["SearchProviders"]));
            }
            set {
                this["SearchProviders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockMetro {
            get {
                return ((bool)(this["BlockMetro"]));
            }
            set {
                this["BlockMetro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SquareButton {
            get {
                return ((bool)(this["SquareButton"]));
            }
            set {
                this["SquareButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WatchRemovables {
            get {
                return ((bool)(this["WatchRemovables"]));
            }
            set {
                this["WatchRemovables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnBadConfig {
            get {
                return ((bool)(this["WarnBadConfig"]));
            }
            set {
                this["WarnBadConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ArIndex {
            get {
                return ((int)(this["ArIndex"]));
            }
            set {
                this["ArIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ArFollowsTaskbar {
            get {
                return ((bool)(this["ArFollowsTaskbar"]));
            }
            set {
                this["ArFollowsTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartImage {
            get {
                return ((string)(this["StartImage"]));
            }
            set {
                this["StartImage"] = value;
            }
        }
    }
}
