//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Power8.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NoLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Power8.Properties.NoLoc", typeof(NoLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type constructor did not return the type object..
        /// </summary>
        internal static string Err_GotNoTypeObject {
            get {
                return ResourceManager.GetString("Err_GotNoTypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type disposition event cannot be reacted on..
        /// </summary>
        internal static string Err_TypeIsNotIComponent {
            get {
                return ResourceManager.GetString("Err_TypeIsNotIComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an unhandled exceptoion occured in Power8. Details are below.
        ///.
        /// </summary>
        internal static string Err_UnhandledGeneric {
            get {
                return ResourceManager.GetString("Err_UnhandledGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power8.
        /// </summary>
        internal static string Stg_AppShortName {
            get {
                return ResourceManager.GetString("Stg_AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svn/trunk/Properties/AssemblyInfo.cs.
        /// </summary>
        internal static string Stg_AssemblyInfoURI {
            get {
                return ResourceManager.GetString("Stg_AssemblyInfoURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://power8.googlecode.com/.
        /// </summary>
        internal static string Stg_Power8URI {
            get {
                return ResourceManager.GetString("Stg_Power8URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Run.
        /// </summary>
        internal static string Stg_RegKeyRun {
            get {
                return ResourceManager.GetString("Stg_RegKeyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting because {0}.
        /// </summary>
        internal static string Str_FailFastFormat {
            get {
                return ResourceManager.GetString("Str_FailFastFormat", resourceCulture);
            }
        }
    }
}
